version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-dev-env
    volumes:
      - .:/app  # Mount the current directory for live code updates
      - ./src:/app/src  # Optional: If you want to specifically mount the source code
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered (real-time output)
    ports:
      - "8888:8888"  # Expose a port for Jupyter Notebook or other dev tools
    command: bash  # Keep the container running with a shell
    tty: true  # Keep the container interactive
    stdin_open: true  # Allow interactive commands like testing
    depends_on:
      - test  # Optionally, to ensure tests run when starting

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-test-env
    volumes:
      - .:/app  # Mount the current directory
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m unittest discover -s test  # Run tests from 'test' folder
    tty: true  # Keep the container interactive

volumes:
  app:

